08-16 01:22:18 [ERROR] services | Id：348399122 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
08-16 01:23:09 [ERROR] nonebot | Running Matcher(type='message', module=basic_plugins.help) failed.
Traceback (most recent call last):

  File "/opt/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7efeb21611f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7efeb35841f0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7efeb2b93160>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7efeb2b93310>
    └ <uvicorn.server.Server object at 0x7efe96a40ca0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7efeb2b933a0>
           │       │   └ <uvicorn.server.Server object at 0x7efe96a40ca0>
           │       └ <function run at 0x7efeb319d430>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7efe96a63340>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _event_to_me at 0x7efeb20f89d0>: <Task finished name='Task-3393' coro=<_event_to_me() done, defined at /root/.cach...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7efe95aa4160>
          │            │        │    │      └ {'_prefix': {'command': ('帮助',), 'raw_command': '帮助', 'command_arg': [], 'command_start': ''}}
          │            │        │    └ GroupMessageEvent(time=1692120135, self_id=920935721, post_type='message', sub_type='normal', user_id=552491466, message_type...
          │            │        └ Bot(type='OneBot V11', self_id='920935721')
          │            └ Matcher(type='message', module=basic_plugins.help)
          └ <function _run_matcher at 0x7efeb1f27280>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _event_to_me at 0x7efeb20f89d0>: <Task finished name='Task-3393' coro=<_event_to_me() done, defined at /root/.cach...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7efe95aa4160>
          │       │   │    │      └ {'_prefix': {'command': ('帮助',), 'raw_command': '帮助', 'command_arg': [], 'command_start': ''}}
          │       │   │    └ GroupMessageEvent(time=1692120135, self_id=920935721, post_type='message', sub_type='normal', user_id=552491466, message_type...
          │       │   └ Bot(type='OneBot V11', self_id='920935721')
          │       └ <function Matcher.run at 0x7efeb20f8790>
          └ Matcher(type='message', module=basic_plugins.help)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _event_to_me at 0x7efeb20f89d0>: <Task finished name='Task-3393' coro=<_event_to_me() done, defined at /root/.cach...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7efe95aa4160>
          │    │          │    │      └ {'_prefix': {'command': ('帮助',), 'raw_command': '帮助', 'command_arg': [], 'command_start': ''}}
          │    │          │    └ GroupMessageEvent(time=1692120135, self_id=920935721, post_type='message', sub_type='normal', user_id=552491466, message_type...
          │    │          └ Bot(type='OneBot V11', self_id='920935721')
          │    └ <function Matcher.simple_run at 0x7efeb20f8700>
          └ Matcher(type='message', module=basic_plugins.help)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
          └ Dependent(call=_)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='920935721'), 'event': GroupMessageEvent(time=1692120135, self_id=920935721, post_type...
                 │    │             │         │    │    └ <function _ at 0x7efe9ebc4430>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7efeb348aee0>

  File "/opt/zhenxun_bot/basic_plugins/help/__init__.py", line 58, in _
    await simple_help.send(image(_image_path))
          │           │    │     └ PosixPath('data/group_help/666036653.png')
          │           │    └ <function image at 0x7efe9ecb2310>
          │           └ <classmethod object at 0x7efeb20f2970>
          └ Matcher(type='message', module=basic_plugins.help)

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 461, in send
    return await bot.send(event=event, message=_message, **kwargs)
                 │   │          │              │           └ {}
                 │   │          │              └ MessageSegment(type='image', data={'file': 'file:///opt/zhenxun_bot/data/group_help/666036653.png', 'type': None, 'cache': 't...
                 │   │          └ GroupMessageEvent(time=1692120135, self_id=920935721, post_type='message', sub_type='normal', user_id=552491466, message_type...
                 │   └ <function Bot.send at 0x7efeb1f27700>
                 └ Bot(type='OneBot V11', self_id='920935721')
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
                 │    │                      │     │      │          └ {}
                 │    │                      │     │      └ MessageSegment(type='image', data={'file': 'file:///opt/zhenxun_bot/data/group_help/666036653.png', 'type': None, 'cache': 't...
                 │    │                      │     └ GroupMessageEvent(time=1692120135, self_id=920935721, post_type='message', sub_type='normal', user_id=552491466, message_type...
                 │    │                      └ Bot(type='OneBot V11', self_id='920935721')
                 │    └ <attribute '__class__' of 'object' objects>
                 └ Bot(type='OneBot V11', self_id='920935721')
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/bot.py", line 174, in send
    return await bot.send_msg(**params)
                 │              └ {'user_id': 552491466, 'group_id': 666036653, 'message_type': 'group', 'message': [MessageSegment(type='image', data={'file':...
                 └ Bot(type='OneBot V11', self_id='920935721')
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
          └ NetWorkError(message='WebSocket call api send_msg timeout')
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
                   │    │       │         │     │      └ {'user_id': 552491466, 'group_id': 666036653, 'message_type': 'group', 'message': [MessageSegment(type='image', data={'file':...
                   │    │       │         │     └ 'send_msg'
                   │    │       │         └ Bot(type='OneBot V11', self_id='920935721')
                   │    │       └ <function Adapter._call_api at 0x7efeb1f2c9d0>
                   │    └ Adapter(name='OneBot V11')
                   └ Bot(type='OneBot V11', self_id='920935721')
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/adapters/onebot/v11/adapter.py", line 134, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
          └ <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>

nonebot.adapters.onebot.v11.exception.NetworkError
08-16 01:27:13 [ERROR] services | Id：348399122 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
08-16 01:37:22 [ERROR] services | Id：1197454103 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
08-16 01:38:21 [ERROR] services | Id：348399122 获取信息失败... || 错误 <class 'bilireq.exceptions.ResponseCodeError'>: 错误码: -799, 信息: 请求过于频繁，请稍后再试
08-16 01:50:53 [ERROR] apscheduler | Job "_ (trigger: interval[0:02:00], next run at: 2023-08-16 01:52:45 CST)" raised an exception
Traceback (most recent call last):

  File "/opt/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7f602efbf1f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7f60303e21f0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7f602f9ef160>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7f602f9ef310>
    └ <uvicorn.server.Server object at 0x7f6010fddd30>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7f602f9ef3a0>
           │       │   └ <uvicorn.server.Server object at 0x7f6010fddd30>
           │       └ <function run at 0x7f602fffc430>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f6010e09140>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=1d671fb867f94daf9fc44a6a9f81c2e0 name=_)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=1d671fb867f94daf9fc44a6a9f81c2e0 name=_)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=1d671fb867f94daf9fc44a6a9f81c2e0 name=_)>

  File "/opt/zhenxun_bot/extensive_plugin/zhenxun_plugin_weibo/__init__.py", line 314, in _
    latest_weibos = await spider.get_latest_weibos()
                          │      └ <function BaseWeiboSpider.get_latest_weibos at 0x7f6011286ca0>
                          └ <extensive_plugin.zhenxun_plugin_weibo.weibo_spider.UserWeiboSpider object at 0x7f601127ea00>

  File "/opt/zhenxun_bot/extensive_plugin/zhenxun_plugin_weibo/weibo_spider.py", line 359, in get_latest_weibos
    js = await self.get_weibo_json()
               │    └ <function BaseWeiboSpider.get_weibo_json at 0x7f6011286af0>
               └ <extensive_plugin.zhenxun_plugin_weibo.weibo_spider.UserWeiboSpider object at 0x7f601127ea00>

  File "/opt/zhenxun_bot/extensive_plugin/zhenxun_plugin_weibo/weibo_spider.py", line 301, in get_weibo_json
    js = await self.get_json(
               │    └ <function BaseWeiboSpider.get_json at 0x7f6011286430>
               └ <extensive_plugin.zhenxun_plugin_weibo.weibo_spider.UserWeiboSpider object at 0x7f601127ea00>

  File "/opt/zhenxun_bot/extensive_plugin/zhenxun_plugin_weibo/weibo_spider.py", line 116, in get_json
    r = await client.get(
              │      └ <function ClientSession.get at 0x7f6015a39160>
              └ <aiohttp.client.ClientSession object at 0x7f6009f23f40>

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
                 │    └ None
                 └ <aiohttp.client.ClientSession object at 0x7f6009f23f40>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
                  │    │                  │    │       └ ClientTimeout(total=20, connect=None, sock_read=None, sock_connect=None)
                  │    │                  │    └ []
                  │    │                  └ <aiohttp.client_reqrep.ClientRequest object at 0x7f6008128a90>
                  │    └ <function TCPConnector._create_connection at 0x7f6015af2af0>
                  └ <aiohttp.connector.TCPConnector object at 0x7f60084156a0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
                     │    │                         │    │       └ ClientTimeout(total=20, connect=None, sock_read=None, sock_connect=None)
                     │    │                         │    └ []
                     │    │                         └ <aiohttp.client_reqrep.ClientRequest object at 0x7f6008128a90>
                     │    └ <function TCPConnector._create_direct_connection at 0x7f6015af2e50>
                     └ <aiohttp.connector.TCPConnector object at 0x7f60084156a0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                          │    └ <function TCPConnector._wrap_create_connection at 0x7f6015af2dc0>
                          └ <aiohttp.connector.TCPConnector object at 0x7f60084156a0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
                 │    │     │                  │       └ {'ssl': <ssl.SSLContext object at 0x7f6009f97ec0>, 'family': <AddressFamily.AF_INET: 2>, 'proto': 6, 'flags': <AddressInfo.AI...
                 │    │     │                  └ (functools.partial(<class 'aiohttp.client_proto.ResponseHandler'>, loop=<uvloop.Loop running=True closed=False debug=False>),...
                 │    │     └ <method 'create_connection' of 'uvloop.loop.Loop' objects>
                 │    └ <uvloop.Loop running=True closed=False debug=False>
                 └ <aiohttp.connector.TCPConnector object at 0x7f60084156a0>
  File "uvloop/loop.pyx", line 2029, in create_connection
  File "uvloop/loop.pyx", line 2016, in uvloop.loop.Loop.create_connection

asyncio.exceptions.CancelledError
08-16 03:01:00 [ERROR] services | CMD[自动更新好友] 自动更新好友信息错误 || 错误 <class 'tortoise.exceptions.IntegrityError'>: duplicate key value violates unique constraint "friend_users_user_id_key"
DETAIL:  Key (user_id)=(70395292) already exists.
08-16 07:59:02 [ERROR] apscheduler | Job "todaybefore_reminder (trigger: cron[hour='7', minute='59'], next run at: 2023-08-17 07:59:00 CST)" raised an exception
Traceback (most recent call last):

  File "/opt/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7fa3ca7ca1f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fa3cbbed1f0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7fa3cb1fb160>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7fa3cb1fb310>
    └ <uvicorn.server.Server object at 0x7fa3af2148b0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fa3cb1fb3a0>
           │       │   └ <uvicorn.server.Server object at 0x7fa3af2148b0>
           │       └ <function run at 0x7fa3cb806430>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fa3af223640>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=todaybefore_reminder name=todaybefore_reminder)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=todaybefore_reminder name=todaybefore_reminder)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=todaybefore_reminder name=todaybefore_reminder)>

  File "/opt/zhenxun_bot/extensive_plugin/todaybefore/__init__.py", line 36, in todaybefore_reminder
    for i in groups:

NameError: name 'groups' is not defined
08-16 10:08:43 [ERROR] nonebot | Running Matcher(type='message', module=plugins.sign_in) failed.
Traceback (most recent call last):

  File "/opt/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7fa3ca7ca1f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fa3cbbed1f0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7fa3cb1fb160>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7fa3cb1fb310>
    └ <uvicorn.server.Server object at 0x7fa3af2148b0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fa3cb1fb3a0>
           │       │   └ <uvicorn.server.Server object at 0x7fa3af2148b0>
           │       └ <function run at 0x7fa3cb806430>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fa3af223640>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-2741612' coro=<_command() done, defined at /root/.cache/pyp...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3aefbdaf0>
          │            │        │    │      └ {'_prefix': {'command': ('签到',), 'raw_command': '签到', 'command_arg': [], 'command_start': ''}, '_matched': '签到', '_matched_gr...
          │            │        │    └ GroupMessageEvent(time=1692151722, self_id=920935721, post_type='message', sub_type='normal', user_id=3585425231, message_typ...
          │            │        └ Bot(type='OneBot V11', self_id='920935721')
          │            └ Matcher(type='message', module=plugins.sign_in)
          └ <function _run_matcher at 0x7fa3ca590280>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-2741612' coro=<_command() done, defined at /root/.cache/pyp...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3aefbdaf0>
          │       │   │    │      └ {'_prefix': {'command': ('签到',), 'raw_command': '签到', 'command_arg': [], 'command_start': ''}, '_matched': '签到', '_matched_gr...
          │       │   │    └ GroupMessageEvent(time=1692151722, self_id=920935721, post_type='message', sub_type='normal', user_id=3585425231, message_typ...
          │       │   └ Bot(type='OneBot V11', self_id='920935721')
          │       └ <function Matcher.run at 0x7fa3ca761790>
          └ Matcher(type='message', module=plugins.sign_in)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-2741612' coro=<_command() done, defined at /root/.cache/pyp...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3aefbdaf0>
          │    │          │    │      └ {'_prefix': {'command': ('签到',), 'raw_command': '签到', 'command_arg': [], 'command_start': ''}, '_matched': '签到', '_matched_gr...
          │    │          │    └ GroupMessageEvent(time=1692151722, self_id=920935721, post_type='message', sub_type='normal', user_id=3585425231, message_typ...
          │    │          └ Bot(type='OneBot V11', self_id='920935721')
          │    └ <function Matcher.simple_run at 0x7fa3ca761700>
          └ Matcher(type='message', module=plugins.sign_in)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
          └ Dependent(call=_)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'event': GroupMessageEvent(time=1692151722, self_id=920935721, post_type='message', sub_type='normal', user_id=3585425231, m...
                 │    │             │         │    │    └ <function _ at 0x7fa3b5dcaa60>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7fa3cbaf3ee0>

  File "/opt/zhenxun_bot/plugins/sign_in/__init__.py", line 117, in _
    await group_user_check_in(nickname, event.user_id, event.group_id),
          │                   │         │     │        │     └ 741017215
          │                   │         │     │        └ GroupMessageEvent(time=1692151722, self_id=920935721, post_type='message', sub_type='normal', user_id=3585425231, message_typ...
          │                   │         │     └ 3585425231
          │                   │         └ GroupMessageEvent(time=1692151722, self_id=920935721, post_type='message', sub_type='normal', user_id=3585425231, message_typ...
          │                   └ '潇煋于客'
          └ <function group_user_check_in at 0x7fa3b5dca5e0>

  File "/opt/zhenxun_bot/plugins/sign_in/group_user_checkin.py", line 40, in group_user_check_in
    print("user.checkin_time_last.astimezone(shanghai_tz)", user.checkin_time_last.astimezone(shanghai_tz))
                                                            │    │                 │          └ <DstTzInfo 'Asia/Shanghai' LMT+8:06:00 STD>
                                                            │    │                 └ <method 'astimezone' of 'datetime.datetime' objects>
                                                            │    └ datetime.datetime(1, 1, 1, 0, 0)
                                                            └ <SignGroupUser: 40>

ValueError: year 0 is out of range
08-16 10:29:31 [ERROR] nonebot | Running Matcher(type='message', module=plugins.mute) failed.
Traceback (most recent call last):

  File "/opt/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7fa3ca7ca1f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fa3cbbed1f0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7fa3cb1fb160>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7fa3cb1fb310>
    └ <uvicorn.server.Server object at 0x7fa3af2148b0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fa3cb1fb3a0>
           │       │   └ <uvicorn.server.Server object at 0x7fa3af2148b0>
           │       └ <function run at 0x7fa3cb806430>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fa3af223640>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-3096437' coro=<_command() done, defined at /root/.cache/pyp...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3aeb8dfa0>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │            │        │    └ GroupMessageEvent(time=1692152969, self_id=920935721, post_type='message', sub_type='normal', user_id=853192151, message_type...
          │            │        └ Bot(type='OneBot V11', self_id='920935721')
          │            └ Matcher(type='message', module=plugins.mute)
          └ <function _run_matcher at 0x7fa3ca590280>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-3096437' coro=<_command() done, defined at /root/.cache/pyp...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3aeb8dfa0>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │       │   │    └ GroupMessageEvent(time=1692152969, self_id=920935721, post_type='message', sub_type='normal', user_id=853192151, message_type...
          │       │   └ Bot(type='OneBot V11', self_id='920935721')
          │       └ <function Matcher.run at 0x7fa3ca761790>
          └ Matcher(type='message', module=plugins.mute)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-3096437' coro=<_command() done, defined at /root/.cache/pyp...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3aeb8dfa0>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │    │          │    └ GroupMessageEvent(time=1692152969, self_id=920935721, post_type='message', sub_type='normal', user_id=853192151, message_type...
          │    │          └ Bot(type='OneBot V11', self_id='920935721')
          │    └ <function Matcher.simple_run at 0x7fa3ca761700>
          └ Matcher(type='message', module=plugins.mute)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
          └ Dependent(call=_)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='920935721'), 'event': GroupMessageEvent(time=1692152969, self_id=920935721, post_type...
                 │    │             │         │    │    └ <function _ at 0x7fa3b0b013a0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7fa3cbaf3ee0>

  File "/opt/zhenxun_bot/plugins/mute.py", line 111, in _
    img_hash += await download_img_and_hash(img)
    │                 │                     └ 'https://gchat.qpic.cn/gchatpic_new/853192151/2168794340-3016784118-9F2B561BBC8A87E8605E11C792F4FF34/0?term=2&is_origin=0'
    │                 └ <function download_img_and_hash at 0x7fa3b0b01280>
    └ ''

  File "/opt/zhenxun_bot/plugins/mute.py", line 96, in download_img_and_hash
    imagehash.average_hash(Image.open(BytesIO((await AsyncHttpx.get(url)).content)))
    │         │            │     │    │              │          │   └ 'https://gchat.qpic.cn/gchatpic_new/853192151/2168794340-3016784118-9F2B561BBC8A87E8605E11C792F4FF34/0?term=2&is_origin=0'
    │         │            │     │    │              │          └ <classmethod object at 0x7fa3b748b2b0>
    │         │            │     │    │              └ <class 'utils.http_utils.AsyncHttpx'>
    │         │            │     │    └ <class '_io.BytesIO'>
    │         │            │     └ <function open at 0x7fa3bb2f2820>
    │         │            └ <module 'PIL.Image' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/PIL/Image....
    │         └ <function average_hash at 0x7fa3bad9db80>
    └ <module 'imagehash' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/imagehash/...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/PIL/Image.py", line 3186, in open
    raise UnidentifiedImageError(
          └ <class 'PIL.UnidentifiedImageError'>

PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa3ae060220>
08-16 11:38:19 [ERROR] nonebot | Running Matcher(type='message', module=plugins.mute) failed.
Traceback (most recent call last):

  File "/opt/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7fa3ca7ca1f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fa3cbbed1f0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7fa3cb1fb160>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7fa3cb1fb310>
    └ <uvicorn.server.Server object at 0x7fa3af2148b0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fa3cb1fb3a0>
           │       │   └ <uvicorn.server.Server object at 0x7fa3af2148b0>
           │       └ <function run at 0x7fa3cb806430>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fa3af223640>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
          │            │        │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-4038658' coro=<_command() done, defined at /root/.cache/pyp...
          │            │        │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3ae262a90>
          │            │        │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │            │        │    └ GroupMessageEvent(time=1692157098, self_id=920935721, post_type='message', sub_type='normal', user_id=1584408682, message_typ...
          │            │        └ Bot(type='OneBot V11', self_id='920935721')
          │            └ Matcher(type='message', module=plugins.mute)
          └ <function _run_matcher at 0x7fa3ca590280>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
          │       │   │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-4038658' coro=<_command() done, defined at /root/.cache/pyp...
          │       │   │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3ae262a90>
          │       │   │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │       │   │    └ GroupMessageEvent(time=1692157098, self_id=920935721, post_type='message', sub_type='normal', user_id=1584408682, message_typ...
          │       │   └ Bot(type='OneBot V11', self_id='920935721')
          │       └ <function Matcher.run at 0x7fa3ca761790>
          └ Matcher(type='message', module=plugins.mute)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
          │    │          │    │      │      │      └ {<function _command at 0x7fa3ca761af0>: <Task finished name='Task-4038658' coro=<_command() done, defined at /root/.cache/pyp...
          │    │          │    │      │      └ <contextlib.AsyncExitStack object at 0x7fa3ae262a90>
          │    │          │    │      └ {'_prefix': {'command': None, 'raw_command': None, 'command_arg': None, 'command_start': None}}
          │    │          │    └ GroupMessageEvent(time=1692157098, self_id=920935721, post_type='message', sub_type='normal', user_id=1584408682, message_typ...
          │    │          └ Bot(type='OneBot V11', self_id='920935721')
          │    └ <function Matcher.simple_run at 0x7fa3ca761700>
          └ Matcher(type='message', module=plugins.mute)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 702, in simple_run
    await handler(
          └ Dependent(call=_)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
                 │    │             │         │    │    │       └ {'bot': Bot(type='OneBot V11', self_id='920935721'), 'event': GroupMessageEvent(time=1692157098, self_id=920935721, post_type...
                 │    │             │         │    │    └ <function _ at 0x7fa3b0b013a0>
                 │    │             │         │    └ Dependent(call=_)
                 │    │             │         └ ~R
                 │    │             └ typing.Awaitable
                 │    └ typing.Callable
                 └ <function cast at 0x7fa3cbaf3ee0>

  File "/opt/zhenxun_bot/plugins/mute.py", line 111, in _
    img_hash += await download_img_and_hash(img)
    │                 │                     └ 'https://gchat.qpic.cn/gchatpic_new/1584408682/2168794340-2925638256-952D6047BD5317E4C93155E6B9727E84/0?term=2&is_origin=0'
    │                 └ <function download_img_and_hash at 0x7fa3b0b01280>
    └ ''

  File "/opt/zhenxun_bot/plugins/mute.py", line 96, in download_img_and_hash
    imagehash.average_hash(Image.open(BytesIO((await AsyncHttpx.get(url)).content)))
    │         │            │     │    │              │          │   └ 'https://gchat.qpic.cn/gchatpic_new/1584408682/2168794340-2925638256-952D6047BD5317E4C93155E6B9727E84/0?term=2&is_origin=0'
    │         │            │     │    │              │          └ <classmethod object at 0x7fa3b748b2b0>
    │         │            │     │    │              └ <class 'utils.http_utils.AsyncHttpx'>
    │         │            │     │    └ <class '_io.BytesIO'>
    │         │            │     └ <function open at 0x7fa3bb2f2820>
    │         │            └ <module 'PIL.Image' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/PIL/Image....
    │         └ <function average_hash at 0x7fa3bad9db80>
    └ <module 'imagehash' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/imagehash/...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/PIL/Image.py", line 3186, in open
    raise UnidentifiedImageError(
          └ <class 'PIL.UnidentifiedImageError'>

PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fa3a8d066d0>
08-16 12:00:00 [ERROR] apscheduler | Job "auto_update_member_info (trigger: cron[hour='12', minute='0'], next run at: 2023-08-17 12:00:00 CST)" raised an exception
Traceback (most recent call last):

  File "/opt/zhenxun_bot/bot.py", line 21, in <module>
    nonebot.run()
    │       └ <function run at 0x7fa3ca7ca1f0>
    └ <module 'nonebot' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__in...

  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
    │                 │       └ {}
    │                 └ ()
    └ <function get_driver at 0x7fa3cbbed1f0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 172, in run
    uvicorn.run(
    │       └ <function run at 0x7fa3cb1fb160>
    └ <module 'uvicorn' from '/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/__in...
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 578, in run
    server.run()
    │      └ <function Server.run at 0x7fa3cb1fb310>
    └ <uvicorn.server.Server object at 0x7fa3af2148b0>
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ None
           │       │   │    └ <function Server.serve at 0x7fa3cb1fb3a0>
           │       │   └ <uvicorn.server.Server object at 0x7fa3af2148b0>
           │       └ <function run at 0x7fa3cb806430>
           └ <module 'asyncio' from '/usr/lib/python3.9/asyncio/__init__.py'>
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7fa3af223640>
           │    └ <method 'run_until_complete' of 'uvloop.loop.Loop' objects>
           └ <uvloop.Loop running=True closed=False debug=False>
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-RCuEOm72-py3.9/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
                   │   │     │   │       │   └ <member 'kwargs' of 'Job' objects>
                   │   │     │   │       └ <Job (id=f476ce02ed2846f8ab1d77da4632f427 name=auto_update_member_info)>
                   │   │     │   └ <member 'args' of 'Job' objects>
                   │   │     └ <Job (id=f476ce02ed2846f8ab1d77da4632f427 name=auto_update_member_info)>
                   │   └ <member 'func' of 'Job' objects>
                   └ <Job (id=f476ce02ed2846f8ab1d77da4632f427 name=auto_update_member_info)>

  File "/opt/zhenxun_bot/extensive_plugin/slave_market/__init__.py", line 310, in auto_update_member_info
    _userids.append(user_info.user_qq)
    │        │      └ <GroupInfoUser: 674>
    │        └ <method 'append' of 'list' objects>
    └ []

AttributeError: 'GroupInfoUser' object has no attribute 'user_qq'
